AWSTemplateFormatVersion: 2010-09-09
Description: This deploys a PHP application using Elastic Beanstalk

Resources:
  #
  # BEGIN ELASTIC BEANSTALK CONFIG
  #

  WebApp:
    Type: AWS::ElasticBeanstalk::Application
    # Explicitly state this to avoid a race condition
    DependsOn: WebAppInstanceProfile
    Properties:
      ApplicationName: Web Application
      Description: AWS Elastic Beanstalk PHP Sample Application

  WebAppVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName: !Ref WebApp
      Description:     WebApp v1.3
      SourceBundle:
        S3Bucket: elastic-beanstalk-sample
        # Copied from https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/tutorials.html
        S3Key:    php.zip

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-beanstalk-environment.html
  WebAppEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:  !Ref WebApp
      Description:      !Sub Environemnt for ${!Ref WebApp}
      TemplateName:     !Ref WebAppConfigurationTemplate
      VersionLabel:     !Ref WebAppVersion

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticbeanstalk-configurationtemplate.html
  WebAppConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:   !Ref WebApp
      Description:       !Sub Configuration for ${!Ref WebApp}
      # Get official list of SolutionStackNames via `aws elasticbeanstalk  list-available-solution-stacks`
      SolutionStackName: 64bit Amazon Linux 2 v3.1.3 running PHP 7.4
      # https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options.html
      OptionSettings:
        - Namespace:  aws:autoscaling:asg
          OptionName: MinSize
          Value:      1

        - Namespace:  aws:autoscaling:asg
          OptionName: MaxSize
          Value:      2

        - Namespace:  aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value:      LoadBalanced

        - Namespace:  aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value:      !GetAtt WebAppInstanceProfile.Arn

  WebAppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref WebAppInstanceProfileRole

  WebAppInstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: WebAppInstanceProfileRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      # https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-attach-managed-policy/
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier

  #
  # END ELASTIC BEANSTALK CONFIG
  #
